//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace D15Cnpm7.Views.Home
{
    public partial class Home_Index
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Button UserInfo;
        protected global::System.Web.UI.WebControls.ImageButton FaceUser;
        protected global::System.Web.UI.WebControls.GridView gvProduct_Ao;
        protected global::System.Web.UI.WebControls.GridView gvProduct_Quan;
        protected global::System.Web.UI.WebControls.GridView gvProductMu;
        protected global::System.Web.UI.WebControls.GridView gvProductTui;
        protected global::System.Web.UI.WebControls.GridView gvProductKDD;
        protected global::System.Web.UI.WebControls.GridView gvProductSon;
        protected global::System.Web.UI.WebControls.GridView gvProductKDA;
        protected global::System.Web.UI.WebControls.GridView gvProductDT;
        protected global::System.Web.UI.WebControls.GridView gvSearchResult;
        protected global::System.Web.UI.WebControls.TextBox searchText;
    }
}
